### ISSUE TITLE
cannot flatten() a sprite when ScrollImage is added to it!

### ISSUE THREAD

**Issue by myflashlab** [krechagames/starling-extensions#4]
in my project I am using ScrollImage and it's just great. I love it :) thank you for that, but when I try to flatten the Sprite which holds the ScrollImage it throws the following error:

[Fault] exception, information=Error: Unsupported display object: starling.extensions.krecha::ScrollImage

would you please suggest something?

**Comment by krechagames** [comment]
Sorry but I can do nothing with. Flatten method is using QuadBatch . ScrollImage is a custom object and cannot be batched, probably some changes in core of Starling can fix that but I’m not sure (but even works, it’s wrong way).
You must throw out ScrollImage from the sprite before flatten it.
