### ISSUE TITLE
ScrollImage not working anymore with Starling 1.5?

### ISSUE THREAD

**Issue by alamboley** [krechagames/starling-extensions#5]
Starling 1.5 rc has been released today, and it seems that ScrollImage isn't working anymore. It's a blank screen now.

**Comment by krechagames** [comment]
Thx for feedback, last time was the problem with rectangle texture, we must check what happens now. Can you test with different profiles? Tomorow we will check changes in new Starling. Hmm almost sure there is some problem in 595 line in shader program...

**Comment by alamboley** [comment]
http://forum.starling-framework.org/topic/starling-15-extensions
